### ISSUE TITLE
To show the guide line from basic, to learn Kilt Development.

### ISSUE THREAD

**Issue by Shayel101** [KILTprotocol/docs#33]
Could you please let me know how do i learn the development of Kilt Protocol. I am a new learner of BlockChain, but also for KILT. If you can show me the Roadmap to learn from the basics to deep, i would be gratitude to you. Thanks.

**Comment by weichweich** [comment]
For using KILT i would recommend to start with [the workshop](https://dev.kilt.io/docs/sdk/workshop/welcome).
After that you could start reading the more detailed guide under the Core Feature section.

if you find any errors open an issue here. :)
