### ISSUE TITLE
Command Error

### ISSUE THREAD

**Issue by Shayel101** [KILTprotocol/docs#34]
![Screenshot 2021-12-06 091650](https://user-images.githubusercontent.com/72087516/144774062-36438ff9-46c9-4849-b954-181dee40acfd.png)
i am learning the development of KILT Protocol from your website, https://dev.kilt.io/docs/sdk/workshop/account; and getting this error, To generate an account, and run this command in Windows terminal, How to configure it please and get the correct output ?

**Comment by ntn-x2** [comment]
Thanks @Shayel101! We will investigate the issue and fix it as soon as possible!

**Comment by weichweich** [comment]
@Shayel101 could you try the latest development release? 

`yarn add @kiltprotocol/sdk-js@0.24.0-15`

**Comment by Shayel101** [comment]
Thank you. It’s working now.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by Shayel101** [comment]
![Screenshot 2021-12-08 185108](https://user-images.githubusercontent.com/72087516/145197532-da240b9d-cb28-450c-b42b-82e5e0ba23bb.png)
![Screenshot 2021-12-08 190041](https://user-images.githubusercontent.com/72087516/145197569-bfabd5fd-11da-4661-859d-b50fd3f9d299.png)
How to fix this error Please ?

**Comment by ntn-x2** [comment]
@Shayel101 you cannot use type annotations in a Javascript file. To do that, please rename `attestersDid.js` to `attestersDid.ts`, and run it with `ts-node` instead of `node`.

Alternatively, remove all type annotations from the JS file and run it as usual.

**Comment by ntn-x2** [comment]
Anyway, we noticed there are some inconsistencies in the SDK docs, and we are working on those. I will then reopen this issue to keep track of it and its fix.

**Comment by Shayel101** [comment]
Yeah, got it. after rename in coding it looks no error. but still now CMD doesn't working. Thanks
![Screenshot 2021-12-08 210941](https://user-images.githubusercontent.com/72087516/145214214-56a57559-9e48-49b7-aa96-9e08494c28ea.png)
![Screenshot 2021-12-08 211030](https://user-images.githubusercontent.com/72087516/145214215-c27c762b-26f2-4718-8d6b-7782bbeb1edd.png)

**Comment by ntn-x2** [comment]
You can install ts-node and typescript with `yarn add -D ts-node typescript`, and then run the script with `yarn ts-node accounts.ts`. Let me know if that fixes it 😊  It's a temporary workaround but it should work.

**Comment by Shayel101** [comment]
![Screenshot 2021-12-08 215545](https://user-images.githubusercontent.com/72087516/145220404-643dbfa3-d21f-4452-9f00-47030f966422.png)

**Comment by ntn-x2** [comment]
From https://stackoverflow.com/a/62099904, maybe this works for you as well?

**Comment by Shayel101** [comment]
Till now haven't figure it out Sir. I have tried several ways in these days.
![Screenshot 2021-12-10 212127](https://user-images.githubusercontent.com/72087516/145580524-8a4707c6-c656-4fb9-9e9b-103d0da76140.png)

**Comment by ntn-x2** [comment]
Can you head over our [Discord server](https://discord.com/invite/HztRqvzbhG) so we can better help you debugging this issue?

**Comment by Shayel101** [comment]
Sir, till now i am getting this error. what could be the solution about it plz ?
![Screenshot 2021-12-20 224507](https://user-images.githubusercontent.com/72087516/146785466-bafb9800-a359-4450-87b4-58ab3e59986c.png)

**Comment by weichweich** [comment]
There was a huge rework of the workshop and the SDK version was updated. Everything should work now. If not please reopen the issue or create a new one.
